export const MOCK_INVOICES = [
  {
    receivingFacility: 'Gula H.C.',
    invoiceNo: 'INV-2026-001',
    date: '2026-03-05',
    receiverName: 'Seid Mohammed',
    sender: 'Amhara Regional State Bureau',
    region: 'Amhara',
    regionCode: 'AMH',
    items: [
      {
        id: 1,
        internalCode: '001',
        description: 'Samsung Galaxy Tablet A9+',
        unit: 'Pcs',
        receivedQty: 1,
        unitCost: 450,
        totalCost: 450,
        batch: 'SN-R92...',
        expiry: '2028-01-01',
        remark: 'Cellular',
      },
      {
        id: 2,
        internalCode: '002',
        description: 'Mobile Charger',
        unit: 'Pcs',
        receivedQty: 1,
        unitCost: 25,
        totalCost: 25,
        batch: 'N/A',
        expiry: 'N/A',
        remark: 'Fast',
      },
    ],
  },
  {
    receivingFacility: 'Bahir Dar Clinic',
    invoiceNo: 'INV-2026-002',
    date: '2026-03-06',
    receiverName: 'Abebe Kebede',
    sender: 'Amhara Regional State Bureau',
    region: 'Amhara',
    regionCode: 'AMH',
    items: [
      {
        id: 1,
        internalCode: '003',
        description: 'Medical Gloves',
        unit: 'Box',
        receivedQty: 50,
        unitCost: 10,
        totalCost: 500,
        batch: 'GLV-123',
        expiry: '2027-12-01',
        remark: '',
      },
    ],
  },
];
